services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mc:
    image: minio/mc:latest
    container_name: mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 admin admin12345 &&
      mc admin user add local myapp-access myapp-secret &&
      mc admin policy attach local readwrite --user myapp-access &&
      echo 'Access Key: myapp-access' &&
      echo 'Secret Key: myapp-secret' &&
      tail -f /dev/null
      "

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-dev:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6379:6379"

volumes:
  minio_data:
  postgres_data:
